### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [leonovS/grid-template-init-project#1]
1)
это не самостоятельный блок.
используйте БЭМ корректно
![image](https://user-images.githubusercontent.com/8464662/144736785-88d0daa5-38cb-4655-96f7-444d873ef3fb.png)
![image](https://user-images.githubusercontent.com/8464662/144736802-66ee1a09-5350-436e-850b-6cb76c8ef08e.png)

2)
Цвет заполнителей не соответствует макету.
![image](https://user-images.githubusercontent.com/8464662/144736866-f5a96b08-8a44-4e7a-b0dd-f1c22f987982.png)

**Comment by leonovS** [comment]
исправил замечания. Сверял с мастером шаблона, всё совпадает вроде в
форме.Единственное в макете нижний бордер совпадает и в активном и
пассивном состоянии по яркости

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 5 дек. 2021 г. в 09:56, Andrey ***@***.***>:

**Comment by Alecto** [comment]
2 ссылочки пришлете?

нд, 5 груд. 2021 о 20:06 Sergey ***@***.***> пише:

**Comment by leonovS** [comment]
https://github.com/leonovS/grid-template-init-project.git

https://leonovs.github.io/grid-template-init-project/

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 5 дек. 2021 г. в 22:11, Andrey ***@***.***>:

**Comment by Alecto** [comment]
не исправлено
![image](https://user-images.githubusercontent.com/8464662/144843552-f92cc99d-f83a-499c-a8c4-f022a15bea0e.png)

**Comment by leonovS** [comment]
сравнил всё, может чего не понимаю!
и ни только я сравнивал, тоже не нашли


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 21:19, сергей леонов ***@***.***>:

**Comment by leonovS** [comment]
вы скрины получили от меня?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 21:21, сергей леонов ***@***.***>:

**Comment by leonovS** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 22:03, сергей леонов ***@***.***>:

**Comment by leonovS** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 22:04, сергей леонов ***@***.***>:

**Comment by Alecto** [comment]
Письмо - да, скрины и ссылки - нет

пн, 6 груд. 2021, 21:03 користувач Sergey ***@***.***> пише:

**Comment by leonovS** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 22:04, сергей леонов ***@***.***>:

**Comment by leonovS** [comment]
https://github.com/leonovS/grid-template-init-project.git

https://leonovs.github.io/grid-template-init-project/


пн, 6 дек. 2021 г. в 22:05, сергей леонов ***@***.***>:

**Comment by Alecto** [comment]
ничего

пн, 6 груд. 2021 р. о 21:05 Sergey ***@***.***> пише:

**Comment by leonovS** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 6 дек. 2021 г. в 22:15, Andrey ***@***.***>:
